### Build flags for all targets

BUILDDIR=../build

CF_ALL          = -Wall# C Flags
#CF_ALL		+= -nostdinc -fno-builtin # uncomment if compiler includes default stdlibrarys
LF_ALL          = -Llibc# Linker Flags
LL_ALL          = -lc# Link Librarys
AF_ALL          =# Assembler Flags

LOCALTARGETNAMES= # set LOCALTARGETNAMES to empty if 'make foo' should always mean srcdir/foo and not srcdir/currentdir/foo
S= # silent: S='1':no color info of the current target, S='': show name of currently precessed target

ifeq (,$(BUILDDIR))
  $(error invalid build options)
endif
$(info === Make ==$(MAKELEVEL)==$(MAKE_RESTARTS)==$(MAKECMDGOALS)===)
ifneq (,$(SRCDIR))

.SUFFIXES:
vpath %.c	$(SRCDIR)
vpath %.h	$(SRCDIR)
vpath %.asm	$(SRCDIR)
vpath Makefile	$(SRCDIR)


### Build tools
CC              = i586-elf-gcc
LD		= i586-elf-ld
AR		= i586-elf-ar
NASM		= nasm
INST		= echo INSTALLcmd
define COMP
		$(CC) -MMD $(CF_ALL) $(CF_TGT) -o $@ -c $<
		@sed 's:\(^\| \)\$(SRCDIR)/:\1:g' <$*.d >$@.d \
		 && sed 's/.*://; s/$$\|\\$$/:/;' <$@.d >>$@.d \
		 ; rm -f $*.d
endef
LINK            = $(LD) $(LF_ALL) $(LF_TGT) -o $@ $^ $(LL_TGT) $(LL_ALL)
ARCHIVE		= $(AR) -crs $@ $?
ASSEMBLE	= $(NASM) -f elf $(AF_ALL) $(AF_TGT) -o $@ $<
ASSEMBLEBIN	= $(NASM) -f bin $(AF_ALL) $(AF_TGT) -o $@ $<
MAKEDIR		= mkdir -p $@

DOMAKEALL:=$(if $(MAKECMDGOALS),$(filter all,$(MAKECMDGOALS)),all)
.PHONY:		all
all:		targets


# General directory independent rules
%.o:		%.asm
		@test $(S) || echo -n '[01;33m$@:[0m '
		$(ASSEMBLE)

%.bin:		%.asm
		@test $(S) || echo -n '[01;33m$@:[0m '
#		sleep 5
		$(ASSEMBLEBIN)

%.o:		%.c
		@test $(S) || echo -n '[01;33m$@:[0m '
		$(COMP)
		@#[ -f $(patsubst %.o,%.dd,$@) ] && touch $(patsubst %.o,%.dd,$@) || true
		@#touch -t 197001010101 $(patsubst %.o,%.d,$@)
#		$(eval include $(patsubst %.o,%.d,$@))

%.a:
		@test $(S) || echo -n '[01;32m$@:[0m '
		$(ARCHIVE)

%:		%.o
		@test $(S) || echo -n '[01;32m$@:[0m '
		$(LINK)

%.dd:		%.c
		@test $(S) || echo '[01;36m$@:[0m '
#		use .o.d if exist
		@$(CC) -MM -MQ $* -MF $@ $(CF_ALL) $(CF_TGT) $<
#		generate dependencies of target (all included .h files which have a .c file (all .o files))
		@(echo "$*: $*.o " \
		&& ls xXxXx $$(sed -e '1s/[^ ]* [^ ]*//; s/\\$$\|$$/ /; s/\.h /.c /g' <$@) 2>/dev/null) \
		| sed -e 's/$$/ \\/; $$s/\\$$//; s/\.c /.o /g' >$@~ \
		&& sed -e '1s/:/.dd:/' <$@ >>$@~ \
		&& sed -e '1s/.*://; s/$$\|\\$$/:/' <$@ >>$@~ \
		&& sed -e 's:\(^\| \)\$(SRCDIR)/:\1:g;' <$@~ >$@ \
		; rm $@~

# .d files for non targets dont need to be remade prior to compiling (they are only interesting for the next run)
%.o.d: ;

DOCLEAN=$(filter clean clean.d,$(MAKECMDGOALS))
.PHONY:		clean.d
clean.d:
		rm -f  $(strip $(DEP_OBJ) $(DEP_TGT))
.PHONY:		clean
clean:
ifneq (,$(filter-out clean,$(MAKECMDGOALS)))
		$(error clean must be executed alone)
else
		rm -f $(strip $(TGT_BIN) $(TGT_SBIN) $(TGT_ETC) $(TGT_LIB) $(OBJ) $(DEP_OBJ) $(DEP_TGT))
		$(eval CLEANDIRS:=$(wildcard $(DIR_BUILD)))
		$(if $(CLEANDIRS),rmdir $(CLEANDIRS),)
endif

DOMAKEALL:=$(strip $(DOMAKEALL) $(filter install,$(MAKECMDGOALS)))
.PHONY:		install
install:	targets 
		$(error no install routine present)
		$(INST) $(TGT_BIN) -m 755 -d $(DIR_BIN)
		$(CMD_INSTBIN)
		$(INST) $(TGT_SBIN) -m 750 -d $(DIR_SBIN)
		$(CMD_INSTSBIN)
ifeq ($(wildcard $(DIR_ETC)/*),)
		$(INST) $(TGT_ETC) -m 644 -d $(DIR_ETC)
		$(CMD_INSTETC)
else
		@echo Configuration directory $(DIR_ETC) already present -- skipping
endif
		$(INST) $(TGT_LIB) -m 750 -d $(DIR_LIB)
		$(CMD_INSTLIB)

DOMAKEALL:=$(strip $(DOMAKEALL) $(if $(filter run,$(MAKECMDGOALS)),$(if $(filter-out run,$(MAKECMDGOALS)),,run),))
.PHONY:		run
run:		$(if $(DOMAKEALL),all,$(filter-out run,$(MAKECMDGOALS)))
		@rTGTS='$(if $(DOMAKEALL),$(TGT_BIN),$(filter $(filter-out run all install clean,$(MAKECMDGOALS)),$(TGT_BIN)))'; \
		if [ -n "$$rTGTS" ];then \
			set -- $$rTGTS; \
			if [ -z "$$2"  ];then \
				GO=$$1; \
			else \
				PS3='run which bin? '; \
				select bin in $$rTGTS;do \
					if [ -n "$$bin" ];then \
						GO=$$bin; \
						break; \
					else \
						echo 'invalid selection'; \
					fi; \
				done; \
			fi; \
			test $(S) || echo '[01;33mRUNNING: '$$GO'[0m ' && echo "RUNNING: $$GO" | sed 's/./-/g; s/^/[01;33m/; s/$$/[0m/'; \
			./$$GO; \
		else \
			echo 'theres nothing to run'; \
		fi


define SUBDIR_template
  sp 		:= $$(sp).x
  dirstack_$$(sp):= $$(d)
  d		:= $$(patsubst ./%,%,$$(d)$(1)/)
  #$$(info ==$$(sp)==$$(d)== )

  include	$(2)

  ifeq (,$$(DOCLEAN))
    -include $$(DEP_OBJ_$$(d))
    NEWINCS:=$$(filter-out $$(wildcard $$(DEP_TGT_$$(d))),$$(DEP_TGT_$$(d)))
    ifneq (,$$(NEWINCS))
      $$(shell [ -e ./$$(d) ] || mkdir -p ./$$(d); touch -t 197001010101 $$(NEWINCS))
    endif
    include $$(DEP_TGT_$$(d))
  endif

  ifneq (,$$(filter-out $$(wildcard $$(d)),$$(d)))
#  this can cause make -j to fail (prune prematurely)
#    $$(TGT_BIN_$$(d)) $$(TGT_SBIN_$$(d)) $$(TGT_ETC_$$(d)) $$(TGT_LIB_$$(d)) $$(OBJ_$$(d)) $$(DEP_OBJ_$$(d)) $$(DEP_TGT_$$(d)) :	| $$(d)
#    $$(d):
#		@$$(MAKEDIR)
#  workaround:
    $$(shell mkdir -p $$(d))
  endif

  TGT_BIN	+= $$(TGT_BIN_$$(d))
  TGT_SBIN	+= $$(TGT_SBIN_$$(d))
  TGT_ETC	+= $$(TGT_ETC_$$(d))
  TGT_LIB	+= $$(TGT_LIB_$$(d))
  OBJ		+= $$(OBJ_$$(d))
  DEP_OBJ	+= $$(DEP_OBJ_$$(d))
  DEP_TGT	+= $$(DEP_TGT_$$(d))
  DIR_BUILD	+= $$(d)

#  CLEAN:=$$(CLEAN) $$(TGT_BIN) $$(TGT_SBIN) $$(TGT_ETC) $$(TGT_LIB) $$(OBJS_$$(d))
#  CLEANDEPS:=$$(CLEANDEPS) $$(DEPS_$$(d)) $$(TGTDEPS_$$(d)))
#  CLEANDIR:=$$(CLEANDIR) $$(d)
  d		:= $$(dirstack_$$(sp))
  sp		:= $$(basename $$(sp))
endef


TGT_BIN		:=
TGT_SBIN	:=
TGT_ETC		:=
TGT_LIB		:=
OBJ		:=
DEP_OBJ		:=
DEP_TGT		:=
DIR_BUILD	:=

DIRS	:= . # include Makefile from same directory
ifneq (,$(DIRS))
  $(foreach DIR,$(DIRS),$(eval $(call SUBDIR_template,$(DIR),$(SRCDIR)/Makefile)))
endif

# The variables TGT_*, CLEAN and CMD_INST* may be added to by the Makefile
# fragments in the various subdirectories.

.PHONY:		targets
targets:	$(TGT_BIN) $(TGT_SBIN) $(TGT_ETC) $(TGT_LIB)

# Prevent make from removing any build targets, including intermediate ones
.SECONDARY:	$(TGT_BIN) $(TGT_SBIN) $(TGT_ETC) $(TGT_LIB) $(OBJ) $(DEP_OBJ) $(DEP_TGT) $(DIR_BUILD)



else # no SRCDIR (initialization required)

.PHONY:		all $(MAKECMDGOALS)
all $(filter-out all,$(MAKECMDGOALS)) :
	@# get relative path and call make (two times if "make clean othertarget")
	@[ -n "$(DIDIT)" ] || { \
		absrootdir="$$(cd ./$(ROOTDIR); pwd)"; \
		[ "$$absrootdir" != "$(CURDIR)" $(if $(LOCALTARGETNAMES),,-a 1 -eq 2) ] && { LOCAL=$$(echo '$(CURDIR)'|cut -c $$(expr length "  $$absrootdir")-); [ -n "$$LOCAL" ] && LOCAL=$$LOCAL/;} || LOCAL=; \
		cGOAL=;aGOAL=;lGOAL=; for G in $(MAKECMDGOALS);do echo $$G|grep -qs '^\(all\|clean.*\|run\|install\)$$' \
			&& { echo $$G|grep -qs 'clean.*'&&cGOAL+="$$G "||aGOAL+="$$G ";} || lGOAL+=$$(echo "$$LOCAL$$G "|sed ':a;s|[^/]*/\.\./||;ta') ;done; \
		[ "$(BUILDDIR)" != . ] \
		&&	reversepath="$$(echo $$absrootdir | sed 's|^|\n|; :a;s|\([^\n]*\)\n\(.*\)/\(.*\)|\1/\3\n\2|;ta; s/\n$$//')" && \
			regexp="$$(echo $$reversepath | sed 's~/[^/]*~s|/:\\([^:]*\\)$$|&\\1|;  ~g')" && \
			srcdir=$$(echo $(BUILDDIR) |rev| sed 's|\(/*\)\.\.\(/*\)|\1:\2|g; s|[^/:.]\+/*|../|g' | sed "$$regexp") \
		||	srcdir=.; \
		mkdir -p ./$(ROOTDIR)/$(BUILDDIR); cd ./$(ROOTDIR)/$(BUILDDIR); cd "$$srcdir"; \
		[ "$$absrootdir" != "$$(pwd)" ] && { echo "Relative path did not match [ '$$absrootdir/''$(BUILDDIR)/''$$srcdir' is '$$(pwd)' and not '$(CURDIR)/$(ROOTDIR)' ]"; exit 2; } || { \
			[ -n "$$cGOAL" ] \
				&& { $(MAKE) --no-print-directory -C "$(BUILDDIR)" -f $$srcdir/Makefile.root SRCDIR="$$srcdir" $$cGOAL || endmake=y; }; \
			[ \( -z "$(MAKECMDGOALS)" -o -n "$$aGOAL$$lGOAL" \) -a -z "$$endmake" ] && mkdir -p $(BUILDDIR) \
				&& { $(MAKE) --no-print-directory -C "$(BUILDDIR)" -f $$srcdir/Makefile.root SRCDIR="$$srcdir" $$lGOAL $$aGOAL ; }; : ; \
		}; \
	};
	$(eval DIDIT=yes)
endif
# shorten debug-output
.SUFFIXES:
Makefile Makefile.root : ;
#%.c %.h %.o : ;
